createOrReplace

	ref table 'Measures Technical'

		/// Počet aktuálních žádostí v TRAIN datasetu.
		/// Tabulka factApplications má mít jeden řádek pro jednu aktuální žádost.
		measure 'Applications Count' =
				
				COUNTROWS ( factApplications )
			formatString: #,0
			displayFolder: 01 Základní metriky\Žádosti

		/// Celkový objem aktuálně požadovaného úvěru.
		/// Používá se jako váha pro objemovou distribuci žádostí.
		measure 'Credit Volume' =
				
				SUM ( factApplications[AMT_CREDIT] )
			formatString: #,0
			displayFolder: 01 Základní metriky\Žádosti

		/// Průměrná výše požadovaného úvěru na jednu aktuální žádost.
		measure 'Average Credit Amount' =
				
				DIVIDE (
				    [Credit Volume],
				    [Applications Count]
				)
			formatString: #,0.00
			displayFolder: 01 Základní metriky\Žádosti

		/// Celkový roční příjem klientů v aktuálním kontextu filtru.
		/// Používá se jako jmenovatel ve výpočtu DTI.
		measure 'Annual Income' =
				
				SUM ( factApplications[AMT_INCOME_TOTAL] )
			formatString: #,0
			displayFolder: 01 Základní metriky\Příjem

		/// Výše úvěru aktuálně požadované žádosti v aktuálním kontextu filtru.
		/// Používá se jako část DTI za aktuální kontrakt.
		measure 'Current Application Credit' =
				
				SUM ( factApplications[AMT_CREDIT] )
			formatString: #,0
			displayFolder: 01 Základní metriky\Žádosti

		/// Počet žádostí, kde TARGET = 1.
		/// To znamená, že klient měl problém se splácením.
		measure 'Repayment Difficulty Applications' =
				
				CALCULATE (
				    [Applications Count],
				    dimApplicant[TARGET] = 1
				)
			formatString: #,0
			displayFolder: 01 Základní metriky\Rizikový výsledek

		/// Počet žádostí, kde TARGET = 0.
		/// To znamená, že klient neměl pozorovaný problém se splácením.
		measure 'No Repayment Difficulty Applications' =
				
				CALCULATE (
				    [Applications Count],
				    dimApplicant[TARGET] = 0
				)
			formatString: #,0
			displayFolder: 01 Základní metriky\Rizikový výsledek

		/// Podíl žádostí s problémem se splácením v aktuálním kontextu filtru.
		measure 'Repayment Difficulty Rate' =
				
				DIVIDE (
				    [Repayment Difficulty Applications],
				    [Applications Count]
				)
			formatString: 0.00%
			displayFolder: 01 Základní metriky\Rizikový výsledek

		/// Celkový počet žádostí v aktuálním výběru reportu.
		/// Používá se jako jmenovatel pro jednotkovou distribuci.
		measure 'Applications Visible Total' =
				
				CALCULATE (
				    [Applications Count],
				    ALLSELECTED ()
				)
			formatString: #,0
			displayFolder: 02 Distribuce\Počet žádostí

		/// Jednotková distribuce žádostí v procentech.
		/// Použijte s dimenzemi jako pohlaví, věková skupina, vzdělání,
		/// rodinný stav nebo skupina počtu předchozích žádostí.
		measure 'Applications % of Visible Total' =
				
				DIVIDE (
				    [Applications Count],
				    [Applications Visible Total]
				)
			formatString: 0.00%
			displayFolder: 02 Distribuce\Počet žádostí

		/// Celkový objem požadovaného úvěru v aktuálním výběru reportu.
		/// Používá se jako jmenovatel pro objemovou distribuci.
		measure 'Credit Volume Visible Total' =
				
				CALCULATE (
				    [Credit Volume],
				    ALLSELECTED ()
				)
			formatString: #,0
			displayFolder: 02 Distribuce\Objem úvěru

		/// Objemová distribuce žádostí v procentech, kde váhou je AMT_CREDIT.
		/// Použijte s demografickými dimenzemi.
		measure 'Credit Volume % of Visible Total' =
				
				DIVIDE (
				    [Credit Volume],
				    [Credit Volume Visible Total]
				)
			formatString: 0.00%
			displayFolder: 02 Distribuce\Objem úvěru

		/// Součet AMT_CREDIT_SUM za aktivní kontrakty v úvěrovém registru.
		/// Ve výpočtu DTI představuje existující aktivní zadlužení klienta.
		measure 'Active Bureau Credit Exposure' =
				
				COALESCE (
				    CALCULATE (
				        SUM ( factBureauCredits[Active Bureau Credit Sum] ),
				        REMOVEFILTERS ( dimCreditType )
				    ),
				    0
				)
			formatString: #,0
			displayFolder: 03 DTI\Aktivní bureau expozice

		/// Debt To Income poměr.
		/// Počítá se jako aktivní bureau expozice plus aktuálně požadovaný úvěr
		/// děleno ročním příjmem klienta.
		measure 'DTI' =
				
				DIVIDE (
				    [Active Bureau Credit Exposure] + [Current Application Credit],
				    [Annual Income]
				)
			formatString: 0.00
			displayFolder: 03 DTI\Klientská úroveň

		/// Medián klientského DTI v aktuálním kontextu.
		/// Použijte s dimApplicant[Income Type] pro výpočet podle typu příjmu.
		measure 'Median DTI' =
				
				MEDIANX (
				    FILTER (
				        VALUES ( dimApplicant[SK_ID_CURR] ),
				        CALCULATE ( SUM ( factApplications[AMT_INCOME_TOTAL] ) ) > 0
				    ),
				    [DTI]
				)
			formatString: 0.00
			displayFolder: 03 DTI\Analýza podle typu příjmu

		/// Počet žádostí v TRAIN datasetu, kde aktuální typ kontraktu je Cash loans.
		measure 'Cash Applications Count' =
				
				CALCULATE (
				    [Applications Count],
				    dimApplicant[Is Cash Application] = TRUE ()
				)
			formatString: #,0
			displayFolder: 04 Bureau trend\Cash žádosti

		/// Pevný jmenovatel pro trend no-DPD kontraktů.
		/// Počítá všechny TRAIN cash žádosti a ignoruje filtry z bureau historie.
		measure 'Cash Applications Count - Trend Denominator' =
				
				CALCULATE (
				    [Applications Count],
				    dimApplicant[Is Cash Application] = TRUE (),
				    REMOVEFILTERS ( dimCreditType ),
				    REMOVEFILTERS ( dimBureauStatus ),
				    REMOVEFILTERS ( dimRelativeMonth ),
				    REMOVEFILTERS ( factBureauCredits ),
				    REMOVEFILTERS ( factBureauMonthlyStatus )
				)
			formatString: #,0
			displayFolder: 04 Bureau trend\Cash žádosti

		/// Počet unikátních kontraktů v externím úvěrovém registru.
		measure 'Bureau Contracts Count' =
				
				DISTINCTCOUNT ( factBureauCredits[SK_ID_BUREAU] )
			formatString: #,0
			displayFolder: 04 Bureau trend\Bureau kontrakty

		/// Počet unikátních bureau kontraktů se statusem 0 v daném relativním měsíci.
		/// Status 0 znamená bez prodlení.
		measure 'No DPD Bureau Contracts' =
				
				CALCULATE (
				    DISTINCTCOUNT ( factBureauMonthlyStatus[SK_ID_BUREAU] ),
				    REMOVEFILTERS ( dimBureauStatus ),
				    factBureauMonthlyStatus[STATUS] = "0"
				)
			formatString: #,0
			displayFolder: 04 Bureau trend\No DPD

		/// Počet no-DPD bureau kontraktů napojených na TRAIN cash žádosti.
		measure 'No DPD Bureau Contracts - Cash Applications' =
				
				CALCULATE (
				    [No DPD Bureau Contracts],
				    dimApplicant[Is Cash Application] = TRUE ()
				)
			formatString: #,0
			displayFolder: 04 Bureau trend\No DPD

		/// Průměrný počet no-DPD bureau kontraktů na jednu TRAIN cash žádost
		/// podle relativního měsíce.
		/// Použijte dimRelativeMonth na osu a dimCreditType jako filtr CREDIT_TYPE.
		measure 'Avg No DPD Bureau Contracts per Cash Application' =
				
				DIVIDE (
				    [No DPD Bureau Contracts - Cash Applications],
				    [Cash Applications Count - Trend Denominator]
				)
			formatString: 0.000
			displayFolder: 04 Bureau trend\No DPD

		/// Celkový počet historických splátek v nejnovější verzi splátkového kalendáře.
		measure 'Installment Count' =
				
				SUM ( factInstallmentDPD5Summary[InstallmentCount] )
			formatString: #,0
			displayFolder: 05 Bonus DPD5\Splátky

		/// Počet historických splátek, u kterých klient překročil DPD5.
		measure 'DPD5 Installment Count' =
				
				SUM ( factInstallmentDPD5Summary[DPD5InstallmentCount] )
			formatString: #,0
			displayFolder: 05 Bonus DPD5\Splátky

		/// Počet TRAIN žádostí, u kterých klient někdy překročil DPD5
		/// na libovolné předchozí Home Credit žádosti.
		measure 'Applications Ever DPD5' =
				
				SUM ( factInstallmentDPD5Summary[EverDPD5Unit] )
			formatString: #,0
			displayFolder: 05 Bonus DPD5\Úroveň žádosti

		/// Počet TRAIN žádostí, u kterých klient nemá pozorovanou historickou DPD5 událost.
		measure 'Applications Never DPD5' =
				
				[Applications Count] - [Applications Ever DPD5]
			formatString: #,0
			displayFolder: 05 Bonus DPD5\Úroveň žádosti

		/// Podíl TRAIN žádostí, u kterých klient někdy překročil DPD5
		/// na libovolné předchozí Home Credit žádosti.
		measure 'Ever DPD5 Application Ratio' =
				
				DIVIDE (
				    [Applications Ever DPD5],
				    [Applications Count]
				)
			formatString: 0.00%
			displayFolder: 05 Bonus DPD5\Úroveň žádosti

		/// Počet TRAIN žádostí, které mají alespoň jeden historický záznam ve splátkové historii.
		measure 'Applications With Installment History' =
				
				COUNTROWS (
				    FILTER (
				        factInstallmentDPD5Summary,
				        factInstallmentDPD5Summary[InstallmentCount] > 0
				    )
				)
			formatString: #,0
			displayFolder: 05 Bonus DPD5\Pokrytí dat

		/// Počet TRAIN žádostí bez pozorovaného historického záznamu ve splátkové historii.
		measure 'Applications Without Installment History' =
				
				[Applications Count] - [Applications With Installment History]
			formatString: #,0
			displayFolder: 05 Bonus DPD5\Pokrytí dat

		/// Podíl TRAIN žádostí, které mají dostupnou historickou splátkovou historii.
		measure 'Installment History Coverage %' =
				
				DIVIDE (
				    [Applications With Installment History],
				    [Applications Count]
				)
			formatString: 0.00%
			displayFolder: 05 Bonus DPD5\Pokrytí dat