table Date
	lineageTag: 333b0a96-b3e2-4d2e-9f2a-7b3e492cc63c

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8c503fff-0102-4a8c-8efb-180c6dea95c5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Num'
		dataType: int64
		formatString: 0
		lineageTag: 67fcfe87-c8a9-4526-804d-e3dbbb65a82a
		summarizeBy: none
		sourceColumn: Date Num

		annotation SummarizationSetBy = User

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 30ceb31d-da4e-43e1-b302-664df68f3e40
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Month
		dataType: string
		lineageTag: 778cb040-b247-4465-9c1b-7166b994b65d
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Num'
		dataType: int64
		formatString: 0
		lineageTag: c95c09a4-98cc-4fa7-b4ea-3bcc718ca1db
		summarizeBy: none
		sourceColumn: Month Num

		annotation SummarizationSetBy = User

	column 'Month Long'
		dataType: string
		lineageTag: a18b49c9-821a-4442-b576-5bcc8fedce62
		summarizeBy: none
		sourceColumn: Month Long
		sortByColumn: 'Month Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Day Num'
		dataType: int64
		formatString: 0
		lineageTag: cbf89a64-0c09-47e2-8a2e-ef90090898ef
		summarizeBy: none
		sourceColumn: Month Day Num

		annotation SummarizationSetBy = User

	column 'Year Month'
		dataType: string
		lineageTag: 9232d0ca-c80a-4e91-a26a-7b902cd8b914
		summarizeBy: none
		sourceColumn: Year Month
		sortByColumn: 'Year Month Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Month Num'
		dataType: string
		lineageTag: 54938c48-d697-42fa-8127-d782f83117d2
		summarizeBy: none
		sourceColumn: Year Month Num

		annotation SummarizationSetBy = Automatic

	column 'Year Month Long'
		dataType: string
		lineageTag: f111a6fc-0f19-4f04-8a7b-10150376eef3
		summarizeBy: none
		sourceColumn: Year Month Long
		sortByColumn: 'Year Month Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Month CM'
		dataType: string
		lineageTag: d621b7a6-20dd-4723-8f38-2ba5ff114253
		summarizeBy: none
		sourceColumn: Year Month CM
		sortByColumn: 'Year Month Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Week Num'
		dataType: int64
		formatString: 0
		lineageTag: a2bc1bc8-b46c-43ff-baee-a247d1d455ec
		summarizeBy: none
		sourceColumn: Week Num

		annotation SummarizationSetBy = User

	column Weekday
		dataType: string
		lineageTag: 5ed1b303-ff7e-41d9-869a-e348b499321d
		summarizeBy: none
		sourceColumn: Weekday
		sortByColumn: 'Weekday Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Weekday Num'
		dataType: int64
		formatString: 0
		lineageTag: bab80891-11f9-4a9a-8147-d68c3ad7b05c
		summarizeBy: none
		sourceColumn: Weekday Num

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: 7ac0c5c0-c529-4174-a744-b59b4f6ed63e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Quarter Num'
		dataType: int64
		formatString: 0
		lineageTag: 81ad8d1a-bc0a-4eb2-8943-26403b3f9932
		summarizeBy: none
		sourceColumn: Quarter Num

		annotation SummarizationSetBy = User

	column 'Week Long'
		dataType: string
		lineageTag: ef486a48-28dd-484d-b584-4e28faf379e5
		summarizeBy: none
		sourceColumn: Week Long

		annotation SummarizationSetBy = Automatic

	column 'Year Week Long'
		dataType: string
		lineageTag: 87fd12a4-82c4-43cf-82d8-ebd68e522f02
		summarizeBy: none
		sourceColumn: Year Week Long

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		dataType: string
		lineageTag: ab2cc254-95c2-40dd-95d1-d1f42e8304bc
		summarizeBy: none
		sourceColumn: Year Quarter
		sortByColumn: YearQuarterSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Offset'
		dataType: int64
		formatString: 0
		lineageTag: 9ec2ffd3-2f35-4041-93c7-0aa3d1edee0a
		summarizeBy: sum
		sourceColumn: Month Offset

		annotation SummarizationSetBy = Automatic

	column 'Year Offset'
		dataType: int64
		formatString: 0
		lineageTag: befc599e-d560-4594-929d-ab1c7b7df911
		summarizeBy: sum
		sourceColumn: Year Offset

		annotation SummarizationSetBy = Automatic

	column 'Day Offset'
		dataType: int64
		formatString: 0
		lineageTag: f69d2a47-edbd-434a-826c-5c3afaaca222
		summarizeBy: sum
		sourceColumn: Day Offset

		annotation SummarizationSetBy = Automatic

	column YearMonthSort
		dataType: int64
		formatString: 0
		lineageTag: 9a371ddd-b0c9-436b-b2ff-b614ead95a38
		summarizeBy: sum
		sourceColumn: YearMonthSort

		annotation SummarizationSetBy = Automatic

	column YearQuarterSort
		dataType: int64
		formatString: 0
		lineageTag: 227756c4-a60d-449c-a699-1a55f6ec58e0
		summarizeBy: sum
		sourceColumn: YearQuarterSort

		annotation SummarizationSetBy = Automatic

	column YearWeekSort
		dataType: int64
		formatString: 0
		lineageTag: c4b60bbf-b9b8-472f-a684-ffbd7ca9d56a
		summarizeBy: sum
		sourceColumn: YearWeekSort

		annotation SummarizationSetBy = Automatic

	column IsToday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5bb04f3a-b009-4f9f-b4fc-d66abe8d304e
		summarizeBy: none
		sourceColumn: IsToday

		annotation SummarizationSetBy = Automatic

	partition Date-ffc89e31-c97c-4e27-9609-c4a9af66e791 = m
		mode: import
		queryGroup: CALENDAR
		source = ```
				let
				StartDate = #"_StartDate",
				Today = Date.From(DateTime.LocalNow()), // today's date
				EndDate = #"_EndDate" /*was "#date(2017, 1, 1)" Updated on 201802027: hard Coded End of Year caused some formulas to break, switching to dynamic date*/,
				#"-- Parameters Above --" = 1,
				#"-- Build Dates --" = #"-- Parameters Above --",
				ListDates = List.Dates(StartDate, Number.From(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				#"Converted to Table" = Table.FromList(ListDates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				#"Renamed Columns as Date" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				#"Changed Type to Date" = Table.TransformColumnTypes(#"Renamed Columns as Date",{{"Date", type date}}),
				#"-- Add Calendar Columns --" = #"Changed Type to Date",
				#"Date Number" = Table.AddColumn(#"-- Add Calendar Columns --", "Date Num", each Number.FromText(Text.Combine({Date.ToText(Date.From([Date]), "yyyy"), Date.ToText(Date.From([Date]), "MM"), Date.ToText(Date.From([Date]), "dd")})), Int64.Type),
				Year = Table.AddColumn(#"Date Number", "Year", each Date.Year([Date]), Int64.Type),
				Month = Table.AddColumn(Year, "Month", each Text.Start(Date.MonthName([Date],_Language),3), type text),
				#"Month Num" = Table.AddColumn(Month, "Month Num", each Date.Month([Date]), Int64.Type),
				#"Month Long" = Table.AddColumn(#"Month Num", "Month Long", each Date.MonthName([Date],_Language), type text),
				#"Month Day Num" = Table.AddColumn(#"Month Long", "Month Day Num", each Date.Day([Date]), Int64.Type),
				#"Year Month" = Table.AddColumn(#"Month Day Num", "Year Month", each [Month] & "-" & Text.End(Text.From([Year]),2), type text),
				#"Year Month Num" = Table.AddColumn(#"Year Month", "Year Month Num", each [Year]*100 + [Month Num] /*e.g. Sep-2016 would become 201609*/, Int64.Type),
				#"Year Month Long" = Table.AddColumn(#"Year Month Num", "Year Month Long", each [Month] & "-" & Text.From([Year]), type text),
				#"Year Month CM" = Table.AddColumn(#"Year Month Long", "Year Month CM", each if Date.IsInCurrentMonth([Date]) then "CM" else [Year Month], type text),
				    #"Week Num" = Table.AddColumn(#"Year Month CM", "Week Num" /*ISO8601*/, each if
				Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=0
				then
				Number.RoundDown((Date.DayOfYear(#date(Date.Year([Date])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([Date])-1,12,31), Day.Monday)+1)+10)/7)
				else if
				(Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7)=53
				and (Date.DayOfWeek(#date(Date.Year([Date]),12,31), Day.Monday)+1<4))
				then
				1
				else
				Number.RoundDown((Date.DayOfYear([Date])-(Date.DayOfWeek([Date], Day.Monday)+1)+10)/7), Int64.Type),
				    #"Week Num Long" = Table.AddColumn(#"Week Num", "Week Long", each "W" & Text.End("0"&Number.ToText([Week Num]),2), type text),
				    #"Year Week Long" = Table.AddColumn(#"Week Num Long", "Year Week Long", each if ([Month Num]=1 and [Week Num]>25) 
				then Text.End(Text.From([Year]-1),4) & "-" & [Week Long] else (
				if ([Month Num]=12 and [Week Num]=1) 
				then Text.End(Text.From([Year]+1),4) & "-" & [Week Long]
				else Text.End(Text.From([Year]),4) & "-" & [Week Long]), type text),
				    Weekday = Table.AddColumn(#"Year Week Long", "Weekday", each Text.Start(Date.DayOfWeekName([Date],_Language),3), type text),
				#"Weekday Num" = Table.AddColumn(Weekday, "Weekday Num", each Date.DayOfWeek([Date])+1, Int64.Type),
				Quarter = Table.AddColumn(#"Weekday Num", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				#"Quarter Num" = Table.AddColumn(Quarter, "Quarter Num", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Year Quarter" = Table.AddColumn(#"Quarter Num", "Year Quarter", each Text.From([Year])&"-"&[Quarter], type text),
				#"Today Offset" = Table.AddColumn(#"Year Quarter", "Day Offset", each Duration.Days([Date]-Today), Int64.Type),
				#"Month Offset" = Table.AddColumn(#"Today Offset", "Month Offset", each (([Year]-Date.Year(Today))*12)+([Month Num]-Date.Month(Today)), Int64.Type),
				#"Year Offset" = Table.AddColumn(#"Month Offset", "Year Offset", each [Year]-Date.Year(Today),Int64.Type),
				#"Month Sort" = Table.DuplicateColumn(#"Year Offset", "Year Month Num", "YearMonthSort", Int64.Type),
				#"Quarter Sort" = Table.AddColumn(#"Month Sort", "YearQuarterSort", each Text.From([Year])&Text.From([Quarter Num])),
				#"Week Sort" = Table.AddColumn(#"Quarter Sort", "YearWeekSort", each Text.From([Year])&Text.End([Week Long],2)),
				IsToday = Table.AddColumn(#"Week Sort", "IsToday", each [Date]=DateTime.Date(DateTime.LocalNow()), type logical),
				    #"Changed Type" = Table.TransformColumnTypes(IsToday,{{"Year Month Num", type text}, {"YearQuarterSort", Int64.Type}, {"YearWeekSort", Int64.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

